---
title: Pixel kunst
description: Maak een editor voor pixelillustraties met HTML, CSS en JavaScript.
hero_image: images/pixel-art.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
original_url: https://codeclubprojects.org/en-GB/webdev/pixel-art
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Inleiding
- title: Wat heb je nodig
- title: Maak een raster van pixels
- title: 'Uitdaging: verklein je raster'
- title: Kleur de pixels
  completion:
  - engaged
- title: 'Uitdaging: maak alle pixels klikbaar'
- title: Voeg een kleurenpalet toe
  completion:
  - internal
- title: 'Uitdaging: voeg meer kleuren toe aan het palet'
