---
title: Pixel art
description: Create a pixel art editor using HTML, CSS, and JavaScript.
hero_image: images/pixel-art.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
original_url: https://codeclubprojects.org/en-GB/webdev/pixel-art
interests: art
technologies: html-css-javascript
site_areas: projects
software: html-css-javascript
version: 3
last_tested: 2024-07-08
steps:
  - title: What you will make
  - title: Create a grid of pixels
    completion:
      - engaged
  - title: Add a row of pixels
  - title: Challenge: resize your grid
  - title: Colour the pixels
    completion:
      - internal
  - title: Challenge: make all pixels clickable
  - title: Create a colour palette
  - title: Make the palette interactive
    completion:
      - external
  - title: Challenge: add more colours to the palette