---
title: Artă cu pixeli
description: Creează o editor de artă cu pixeli folosind HTML, CSS și JavaScript.
hero_image: images/pixel-art.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
original_url: https://codeclubprojects.org/ro-RO/webdev/pixel-art
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: De ce vei avea nevoie
  - 
    title: Creează o grilă de pixeli
  - 
    title: 'Provocare: redimensionează-ți grila'
  - 
    title: Colorează pixelii
  - 
    title: 'Provocare: activează click-ul pentru toți pixelii'
  - 
    title: Adaugă o paletă de culori
  - 
    title: 'Provocare: adaugă mai multe culori la paletă'
