---
title: Arte em Pixels
description: Neste projeto, você vai criar um editor de arte em pixels.
hero_image: images/pixel-art.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
original_url: https://codeclubprojects.org/en-GB/webdev/pixel-art
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Introdução
- title: O que você vai precisar
  completion: engaged
- title: Crie uma grade de pixels
- title: 'Desafio: redimensione sua grade'
- title: Colorindo os pixels
- title: 'Desafio: torne todos os pixels clicáveis'
- title: Adicione uma paleta de cores
  completion: internal
- title: 'Desafio: adicione mais cores à paleta'
