---
title: Pikselowa sztuka
description: Stwórz edytor sztuki pikselowej za pomocą HTML, CSS i JavaScript.
hero_image: images/pixel-art.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
original_url: https://codeclubprojects.org/en-GB/webdev/pixel-art
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Wprowadzenie
- title: Czego będziesz potrzebować
  completion: engaged
- title: Utwórz siatkę pikseli
- title: 'Wyzwanie: zmień rozmiar swojej siatki'
- title: Pokoloruj piksele
- title: 'Wyzwanie: spraw, aby wszystkie piksele były klikalne'
- title: Dodaj paletę kolorów
  completion: internal
- title: 'Wyzwanie: dodaj więcej kolorów do palety'
