---
title: Pixel Art
description: Crea un editor di Pixel Art usando HTML, CSS e JavaScript.
hero_image: images/pixel-art.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
original_url: https://codeclubprojects.org/en-GB/webdev/pixel-art
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Introduzione
- title: Di cosa avrai bisogno
  completion: engaged
- title: Crea una griglia di pixel
- title: 'Sfida: ridimensiona la tua griglia'
- title: Colora i pixel
- title: 'Sfida: rendere tutti i pixel selezionabili'
- title: Aggiungi una tavolozza di colori
  completion: internal
- title: 'Sfida: aggiungi più colori alla tavolozza'
